### ISSUE TITLE
Output screenshot after simulation

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-hpc-plugin#34]
Feel++ has a script to create an screenshot after simulation complete. The idea is to set this as an output.

**Comment by victorsndvg** [comment]
Here I have a question (or suggestion, not sure).

Is an screenshot a characteristic of a simulation? or is it (could be) a characteristic of a dataset?

If the screenshot is something that belongs to an input/output dataset, I think the picture should be shown in the data catalogue instead of the experiment tools.

What do you think? it has sense?

**Comment by victorsndvg** [comment]
Going deep into my suggestion...

I think ,It should be a more general solution to show a preview (or link) to an output (or input) dataset from CKan into the portal. In this case the portal doesn't need to talk directly with particular simulations, just improve the relationship with the data catalogue.

To think....
