### ISSUE TITLE
Application logger

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/cloudify-hpc-plugin#54]
Specific logs of each application, showed in the portal.

For each execution, the portal have to show specific logs of the application while it is running.
After the execution, custom outputs (some specifics metrics of the app) could be shown as well.

A way for each application to define how the logs must be read is needed.

**Comment by prudhomm** [comment]
We have already the logs ready to be shown, what are the plans now? I would think that this is must-have feature for ECMI. What do you think?

**Comment by victorsndvg** [comment]
The development is evolving, but it will not be ready for ECMI. too much things to do. We must focus on the priorities decided from the TC

**Comment by prudhomm** [comment]
@victorsndvg just one, not very constructive, remark: we have been discussing monitoring/logging apps almost since day 1, and the lack of this main feature is currently making us waste a lot of previous time.

**Comment by victorsndvg** [comment]
I completely understand you. I'm working really hard to code this from scratch.

In order to provide some future splitting of this epic, here I write down some of the big tasks to be performed:
  - Basic web interface to show logs
  - Client to tail, filter and send logs to server
  - Asynchronous message passing from CLI to the web server
  - Asynchronous message passing through websockets between server and web client
  - Log storage in an efficient json database
  - Oauth authentication
  - Stack deployment

etc.

To think
